title: "Filetango | Fileteado Porteño"
description: "Fileteado porteño por Lautaro"
url: "https://filetango.com.ar"     # dominio propio
baseurl: ""                         # vacío con dominio propio
cat > _config.yml <<'YML'
title: "Filetango | Fileteado Porteño"
description: "Fileteado porteño por Lautaro"
url: "https://filetango.com.ar"     # dominio propio
baseurl: ""                         # vacío con dominio propio

remote_theme: raviriley/agency-jekyll-theme

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
